# some info on where to get the accessibliity networks
build_networks:
  walk:
      name: accessibility/pandana/2015_06_01_osm_bayarea4326.h5
      max_distance: 3000
  drive:
      name: accessibility/pandana/2015_08_03_tmnet.h5
      max_distance: 45
      weight_col: "CTIMEA"