language: python

python:
  - '2.7'
  - '3.6'

install:
  - pip install .  # baus and requirements
  - pip install coverage pycodestyle pytest  # testing tools
  - pip list

script:
  - pycodestyle baus
  - pycodestyle scripts
  - coverage run --source baus --module pytest --verbose

after_success:
  - coverage report
