site_name: Bay Area UrbanSim
site_url: http://bayareametro.github.io/bayarea_urbansim/
repo_url: https://github.com/BayAreaMetro/bayarea_urbansim

theme: 
    name: material
    features:
    - navigation.tabs
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes

nav:
    - Model: 'model.md'
    - Scenarios: 'scenarios.md'
    - Configuration: 'configuration.md'
    - Input: 'input.md'
    - Output: 'output.md'

plugins:
  - autorefs
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_source: true
      watch:
        - baus
  - mike:

extra:
  version:
    provider: mike
    default: main
  