site_name: Bay Area UrbanSim
site_url: https://bayareametro_urbansim.com/
repo_url: https://github.com/BayAreaMetro/bayarea_urbansim

theme: 
    # name: readthedocs
    name: material
    features:
    - navigation.tabs
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes

nav:
    - Home: 'index.md'
    - Configuration: 'configuration.md'
    - Input: 'input.md'
    - Output: 'output.md'
    - Scenarios: 'scenarios.md'

plugins:
  - autorefs
  - mike:

extra:
  version:
    provider: mike
    default: latest