name: Employment Location Choice Model

model_type: locationchoice

choosers_fit_filters: null

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 5000

model_expression: np.log1p(non_residential_rent) + np.log1p(stories) + ave_income
    + sum_nonresidential_units + jobs - 1

fitted: true

log_likelihoods:
    convergence: -13967.051021727528
    'null': -16339.143819886787
    ratio: 0.14517852491586036

fit_parameters:
    Coefficient:
        ave_income: 0.03486952657298216
        jobs: 0.42245483852784765
        np.log1p(non_residential_rent): -3.0
        np.log1p(stories): 1.9878504464122744
        sum_nonresidential_units: -0.147379155912233
    Std. Error:
        ave_income: 0.005937293949264717
        jobs: 0.009238967338651241
        np.log1p(non_residential_rent): 0.04613440943765437
        np.log1p(stories): 0.04022892919407164
        sum_nonresidential_units: 0.01454517009405919
    T-Score:
        ave_income: 5.872966181386463
        jobs: 45.72533087767362
        np.log1p(non_residential_rent): -65.02738490787821
        np.log1p(stories): 49.413456590468115
        sum_nonresidential_units: -10.132515120770456
