# scenarios for hazards models
eq_scenarios:
      enable_in: ["1", "2", "5", "11", "12", "15"]
      # scenarios for futures rounds 2 mitigation
      # rtff is not mitigated
      mitigation: ["11", "15"]