name: hlcm_owner

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 1

choosers_predict_filters:
- hownrent == 1

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + sum_residential_units + ave_income
        + autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.046846580688328324
                ave_income: -0.27479508397212155
                np.log1p(residential_price): -0.1786084747396326
                sum_residential_units: -0.09172914793523508
            Std. Error:
                autoPeakTotal: 0.01192068049337445
                ave_income: 0.01328725312284902
                np.log1p(residential_price): 0.027598103400894733
                sum_residential_units: 0.01056887290305646
            T-Score:
                autoPeakTotal: -3.929857923326256
                ave_income: -20.681105525082423
                np.log1p(residential_price): -6.471766271222902
                sum_residential_units: -8.679179774099424
        fitted: true
        log_likelihoods:
            convergence: -67895.84822203967
            'null': -68197.96528430947
            ratio: 0.004430001115287019
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.09580977465140474
                ave_income: -0.18811940127170068
                np.log1p(residential_price): -0.24083537253896486
                sum_residential_units: -0.06671522619713299
            Std. Error:
                autoPeakTotal: 0.012163581394795949
                ave_income: 0.013143044103347044
                np.log1p(residential_price): 0.027263727844644654
                sum_residential_units: 0.010687296192912555
            T-Score:
                autoPeakTotal: -7.876773422373436
                ave_income: -14.313229096126495
                np.log1p(residential_price): -8.833545211106248
                sum_residential_units: -6.242479387946244
        fitted: true
        log_likelihoods:
            convergence: -67962.32611733211
            'null': -68308.48936877307
            ratio: 0.005067646124805147
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.10402729315869408
                ave_income: 0.3543366583647195
                np.log1p(residential_price): -0.3952869515594749
                sum_residential_units: -0.07930650500238194
            Std. Error:
                autoPeakTotal: 0.012484522998767709
                ave_income: 0.013474926691510623
                np.log1p(residential_price): 0.02833166746864253
                sum_residential_units: 0.010510228785211226
            T-Score:
                autoPeakTotal: -8.332500422239772
                ave_income: 26.295998967323225
                np.log1p(residential_price): -13.952124490977393
                sum_residential_units: -7.545649730667409
        fitted: true
        log_likelihoods:
            convergence: -67609.60943615758
            'null': -68244.0169861693
            ratio: 0.009296163649632372
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.0006703408326991848
                ave_income: 1.766110123040697
                np.log1p(residential_price): -0.22513769445041548
                sum_residential_units: -0.06911984537566168
            Std. Error:
                autoPeakTotal: 0.01363616007829934
                ave_income: 0.014313521406716032
                np.log1p(residential_price): 0.02894596766951993
                sum_residential_units: 0.00972681248721937
            T-Score:
                autoPeakTotal: 0.049159061557657195
                ave_income: 123.38753496480764
                np.log1p(residential_price): -7.777860357644399
                sum_residential_units: -7.106114718103418
        fitted: true
        log_likelihoods:
            convergence: -65319.88359614218
            'null': -68253.22732654127
            ratio: 0.04297736305369426
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
