name: hlcm_owner

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 1

choosers_predict_filters:
- hownrent == 1

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + sum_residential_units + ave_income
        + autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.011853185554963262
                ave_income: -0.29336360689747254
                np.log1p(residential_price): -0.19162419216881416
                sum_residential_units: -0.11071192338809098
            Std. Error:
                autoPeakTotal: 0.01250068743757518
                ave_income: 0.0140834960924397
                np.log1p(residential_price): 0.03165822713179596
                sum_residential_units: 0.010397094379731886
            T-Score:
                autoPeakTotal: -0.9482026979839824
                ave_income: -20.830311236068432
                np.log1p(residential_price): -6.05290344816423
                sum_residential_units: -10.648352255406376
        fitted: true
        log_likelihoods:
            convergence: -67957.04616997836
            'null': -68211.78079486742
            ratio: 0.003734466714116702
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.10941431437748347
                ave_income: -0.2193915222860438
                np.log1p(residential_price): -0.20007529728742282
                sum_residential_units: -0.07775405761917842
            Std. Error:
                autoPeakTotal: 0.012557046485614273
                ave_income: 0.014912547692764826
                np.log1p(residential_price): 0.03327977328229838
                sum_residential_units: 0.010601594112337107
            T-Score:
                autoPeakTotal: -8.713379734862952
                ave_income: -14.711873973921087
                np.log1p(residential_price): -6.011918879082134
                sum_residential_units: -7.334185481473563
        fitted: true
        log_likelihoods:
            convergence: -67817.23498438697
            'null': -68170.33426319357
            ratio: 0.0051796618371172665
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.07812523510951656
                ave_income: 0.37619605629114117
                np.log1p(residential_price): -0.39633223592818884
                sum_residential_units: -0.08532068298729181
            Std. Error:
                autoPeakTotal: 0.013156075388098614
                ave_income: 0.015423046370777264
                np.log1p(residential_price): 0.034846011117764884
                sum_residential_units: 0.010692606116695433
            T-Score:
                autoPeakTotal: -5.938338965447935
                ave_income: 24.39181256719403
                np.log1p(residential_price): -11.373819361669613
                sum_residential_units: -7.979409514961195
        fitted: true
        log_likelihoods:
            convergence: -67677.61915795476
            'null': -68230.20147561135
            ratio: 0.00809879357976262
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.015010656942836164
                ave_income: 1.765222781197689
                np.log1p(residential_price): -0.1863362670460537
                sum_residential_units: -0.0764953394656429
            Std. Error:
                autoPeakTotal: 0.013690100502056286
                ave_income: 0.015722416303190063
                np.log1p(residential_price): 0.03415180071071736
                sum_residential_units: 0.009691772871702557
            T-Score:
                autoPeakTotal: -1.0964606827087593
                ave_income: 112.27426797238076
                np.log1p(residential_price): -5.4561183647214975
                sum_residential_units: -7.892811818670379
        fitted: true
        log_likelihoods:
            convergence: -65458.05051918123
            'null': -68451.24964453855
            ratio: 0.043727457729416774
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
