name: Household Location Choice Model

model_type: locationchoice

choosers_fit_filters:
- tenure == 1

choosers_predict_filters:
- tenure == 1

sample_size: 100

estimation_sample_size: 5000

model_expression: np.log1p(unit_sqft) + sum_residential_units + ave_unit_sqft + ave_lot_sqft
    + ave_income + poor - 1

location_id_col: building_id

coefficients:
- -1.1153017239064833
- 0.44552171926166934
- 1.3783912477668954
- 0.004798126048782571
- -0.37743013473729536
- 0.2916431618002648

fitted: true

