name: !!python/unicode 'hlcmo'

model_type: !!python/unicode 'segmented_locationchoice'

segmentation_col: !!python/unicode 'income_quartile'

choosers_fit_filters:
- !!python/unicode 'tenure <> 1'

choosers_predict_filters:
- !!python/unicode 'tenure <> 1'

alts_fit_filters:
- !!python/unicode 'general_type == ''Residential'''

alts_predict_filters:
- !!python/unicode 'general_type == ''Residential'''

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

default_config:
    !!python/unicode 'model_expression': !!python/unicode 'np.log1p(residential_sales_price)
        + np.log1p(unit_sqft) + sum_residential_units + ave_unit_sqft + ave_lot_sqft
        + ave_income + hhsize + jobs + sfdu + renters + poor + population - 1'

models:
    !!python/unicode '0':
        !!python/unicode 'fit_parameters':
            !!python/unicode 'Coefficient':
                !!python/unicode 'ave_income': 0.06933909231258464
                !!python/unicode 'ave_lot_sqft': 0.056515523806908725
                !!python/unicode 'ave_unit_sqft': 0.16554165831934023
                !!python/unicode 'hhsize': -0.9714201194244565
                !!python/unicode 'jobs': 0.031306882155588085
                !!python/unicode 'np.log1p(residential_sales_price)': -0.3766377621263714
                !!python/unicode 'np.log1p(unit_sqft)': -0.3658474638778532
                !!python/unicode 'poor': 0.8543873878628309
                !!python/unicode 'population': -0.7509125926515913
                !!python/unicode 'renters': 0.5751694898103233
                !!python/unicode 'sfdu': -0.011238812285688623
                !!python/unicode 'sum_residential_units': -0.5184114579890127
            !!python/unicode 'Std. Error':
                !!python/unicode 'ave_income': 0.04320034919894117
                !!python/unicode 'ave_lot_sqft': 0.012751080281213188
                !!python/unicode 'ave_unit_sqft': 0.02309511262115561
                !!python/unicode 'hhsize': 0.11091068832133365
                !!python/unicode 'jobs': 0.012814194992050032
                !!python/unicode 'np.log1p(residential_sales_price)': 0.05378732979943547
                !!python/unicode 'np.log1p(unit_sqft)': 0.015649878215262137
                !!python/unicode 'poor': 0.027748821604015195
                !!python/unicode 'population': 0.06468445409590182
                !!python/unicode 'renters': 0.03137839925800646
                !!python/unicode 'sfdu': 0.007053204705376541
                !!python/unicode 'sum_residential_units': 0.05577273242337751
            !!python/unicode 'T-Score':
                !!python/unicode 'ave_income': 1.6050586071254287
                !!python/unicode 'ave_lot_sqft': 4.432214570100065
                !!python/unicode 'ave_unit_sqft': 7.167822085773272
                !!python/unicode 'hhsize': -8.758579845884917
                !!python/unicode 'jobs': 2.443140764988435
                !!python/unicode 'np.log1p(residential_sales_price)': -7.002350991038124
                !!python/unicode 'np.log1p(unit_sqft)': -23.377016667201282
                !!python/unicode 'poor': 30.790042188285316
                !!python/unicode 'population': -11.608857230800476
                !!python/unicode 'renters': 18.33010935583542
                !!python/unicode 'sfdu': -1.5934334469438358
                !!python/unicode 'sum_residential_units': -9.295070107981962
        !!python/unicode 'fitted': true
        !!python/unicode 'log_likelihoods':
            !!python/unicode 'convergence': -67200.93372204548
            !!python/unicode 'null': -68787.42706811533
            !!python/unicode 'ratio': 0.023063711112480734
        !!python/unicode 'name': 0
    !!python/unicode '1':
        !!python/unicode 'fit_parameters':
            !!python/unicode 'Coefficient':
                !!python/unicode 'ave_income': -0.13859232644187844
                !!python/unicode 'ave_lot_sqft': 0.044256800366247774
                !!python/unicode 'ave_unit_sqft': 0.08713386526584634
                !!python/unicode 'hhsize': -0.22231748484020955
                !!python/unicode 'jobs': 0.050104967013938316
                !!python/unicode 'np.log1p(residential_sales_price)': -0.4898332213352796
                !!python/unicode 'np.log1p(unit_sqft)': -0.3079617840357469
                !!python/unicode 'poor': 0.3784709595638612
                !!python/unicode 'population': -0.32690683386239616
                !!python/unicode 'renters': 0.4705150499053133
                !!python/unicode 'sfdu': -0.03262798173059526
                !!python/unicode 'sum_residential_units': -0.40914807093093947
            !!python/unicode 'Std. Error':
                !!python/unicode 'ave_income': 0.037449715181918364
                !!python/unicode 'ave_lot_sqft': 0.01214545248893213
                !!python/unicode 'ave_unit_sqft': 0.02396674521160014
                !!python/unicode 'hhsize': 0.11192585483820282
                !!python/unicode 'jobs': 0.012036278495601599
                !!python/unicode 'np.log1p(residential_sales_price)': 0.049523292474563545
                !!python/unicode 'np.log1p(unit_sqft)': 0.016005137827767527
                !!python/unicode 'poor': 0.024912822302608998
                !!python/unicode 'population': 0.06778160381401643
                !!python/unicode 'renters': 0.03425207626443536
                !!python/unicode 'sfdu': 0.006974638749937682
                !!python/unicode 'sum_residential_units': 0.05408706372513026
            !!python/unicode 'T-Score':
                !!python/unicode 'ave_income': -3.7007578233544
                !!python/unicode 'ave_lot_sqft': 3.6438988507491157
                !!python/unicode 'ave_unit_sqft': 3.6356152867879903
                !!python/unicode 'hhsize': -1.9862924894483591
                !!python/unicode 'jobs': 4.162828820573411
                !!python/unicode 'np.log1p(residential_sales_price)': -9.890966388934475
                !!python/unicode 'np.log1p(unit_sqft)': -19.24143280424989
                !!python/unicode 'poor': 15.191813876672887
                !!python/unicode 'population': -4.822943327800038
                !!python/unicode 'renters': 13.73683295204673
                !!python/unicode 'sfdu': -4.678089131266732
                !!python/unicode 'sum_residential_units': -7.564619758436593
        !!python/unicode 'fitted': true
        !!python/unicode 'log_likelihoods':
            !!python/unicode 'convergence': -68100.01958580398
            !!python/unicode 'null': -68764.40121718541
            !!python/unicode 'ratio': 0.00966170896017915
        !!python/unicode 'name': 1
    !!python/unicode '2':
        !!python/unicode 'fit_parameters':
            !!python/unicode 'Coefficient':
                !!python/unicode 'ave_income': -0.192024917165353
                !!python/unicode 'ave_lot_sqft': 0.020712278285925607
                !!python/unicode 'ave_unit_sqft': 0.14954287639179098
                !!python/unicode 'hhsize': 0.11335387214174122
                !!python/unicode 'jobs': 0.054643095891118605
                !!python/unicode 'np.log1p(residential_sales_price)': -0.5290424556096892
                !!python/unicode 'np.log1p(unit_sqft)': -0.35038554605974115
                !!python/unicode 'poor': -0.17652140379517106
                !!python/unicode 'population': 0.22430360505126176
                !!python/unicode 'renters': 0.3752313589509639
                !!python/unicode 'sfdu': -0.026266936808851404
                !!python/unicode 'sum_residential_units': -0.3319001681308912
            !!python/unicode 'Std. Error':
                !!python/unicode 'ave_income': 0.04359407206827306
                !!python/unicode 'ave_lot_sqft': 0.012821159010763989
                !!python/unicode 'ave_unit_sqft': 0.024369478573464148
                !!python/unicode 'hhsize': 0.11090233502188092
                !!python/unicode 'jobs': 0.012950860880369307
                !!python/unicode 'np.log1p(residential_sales_price)': 0.05657230495394643
                !!python/unicode 'np.log1p(unit_sqft)': 0.0162574066747462
                !!python/unicode 'poor': 0.025330540772532002
                !!python/unicode 'population': 0.06696413201947672
                !!python/unicode 'renters': 0.03625684565950421
                !!python/unicode 'sfdu': 0.007074520351441205
                !!python/unicode 'sum_residential_units': 0.053828859482316777
            !!python/unicode 'T-Score':
                !!python/unicode 'ave_income': -4.404840109100639
                !!python/unicode 'ave_lot_sqft': 1.615476281710307
                !!python/unicode 'ave_unit_sqft': 6.136482401171594
                !!python/unicode 'hhsize': 1.0221053697325364
                !!python/unicode 'jobs': 4.219263599221089
                !!python/unicode 'np.log1p(residential_sales_price)': -9.351615707374208
                !!python/unicode 'np.log1p(unit_sqft)': -21.55236398213623
                !!python/unicode 'poor': -6.968718330190084
                !!python/unicode 'population': 3.3496081900385475
                !!python/unicode 'renters': 10.349255488876274
                !!python/unicode 'sfdu': -3.7128929600860308
                !!python/unicode 'sum_residential_units': -6.165840616406207
        !!python/unicode 'fitted': true
        !!python/unicode 'log_likelihoods':
            !!python/unicode 'convergence': -68454.06760073971
            !!python/unicode 'null': -68773.61155755738
            !!python/unicode 'ratio': 0.004646316364383951
        !!python/unicode 'name': 2
    !!python/unicode '3':
        !!python/unicode 'fit_parameters':
            !!python/unicode 'Coefficient':
                !!python/unicode 'ave_income': 1.421642553814273
                !!python/unicode 'ave_lot_sqft': 0.06874622128652542
                !!python/unicode 'ave_unit_sqft': 0.09093228485483476
                !!python/unicode 'hhsize': -1.1622282176313525
                !!python/unicode 'jobs': 0.04106190393918635
                !!python/unicode 'np.log1p(residential_sales_price)': -0.25941930285057935
                !!python/unicode 'np.log1p(unit_sqft)': -0.21799736489040825
                !!python/unicode 'poor': -0.21312732695548578
                !!python/unicode 'population': 0.8033326339058668
                !!python/unicode 'renters': -0.16366251084445765
                !!python/unicode 'sfdu': -0.025035851918609686
                !!python/unicode 'sum_residential_units': -0.35148018672184017
            !!python/unicode 'Std. Error':
                !!python/unicode 'ave_income': 0.04627002522198035
                !!python/unicode 'ave_lot_sqft': 0.01266419575172645
                !!python/unicode 'ave_unit_sqft': 0.02696217425162785
                !!python/unicode 'hhsize': 0.1113319284286897
                !!python/unicode 'jobs': 0.013518943442100329
                !!python/unicode 'np.log1p(residential_sales_price)': 0.06158201903232612
                !!python/unicode 'np.log1p(unit_sqft)': 0.017643837276875424
                !!python/unicode 'poor': 0.023733459517217392
                !!python/unicode 'population': 0.06574791845562651
                !!python/unicode 'renters': 0.03788876867618939
                !!python/unicode 'sfdu': 0.006892506472320306
                !!python/unicode 'sum_residential_units': 0.05175404066968245
            !!python/unicode 'T-Score':
                !!python/unicode 'ave_income': 30.7249141748669
                !!python/unicode 'ave_lot_sqft': 5.428392188043491
                !!python/unicode 'ave_unit_sqft': 3.372587240413102
                !!python/unicode 'hhsize': -10.439307340084229
                !!python/unicode 'jobs': 3.037360435380806
                !!python/unicode 'np.log1p(residential_sales_price)': -4.212581966732902
                !!python/unicode 'np.log1p(unit_sqft)': -12.35543954920297
                !!python/unicode 'poor': -8.980036256445166
                !!python/unicode 'population': 12.218373642475674
                !!python/unicode 'renters': -4.319552114326397
                !!python/unicode 'sfdu': -3.632329112660459
                !!python/unicode 'sum_residential_units': -6.791357393041921
        !!python/unicode 'fitted': true
        !!python/unicode 'log_likelihoods':
            !!python/unicode 'convergence': -66871.6530416698
            !!python/unicode 'null': -68856.50462090508
            !!python/unicode 'ratio': 0.028825912528715247
        !!python/unicode 'name': 3

fitted: true

!!python/unicode 'desc': !!python/unicode 'Household Location Choice Model (Owner)'
