name: hlcm_renter

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 2

choosers_predict_filters:
- hownrent == 2

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 1

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(unit_annual_rent / positive_income) + np.log1p(residential_units)
        + np.log1p(pct_renters) + ave_income + np.log1p(white * pct_white) + np.log1p(black
        * pct_black) + np.log1p(hisp * pct_hisp) + np.log1p(asian * pct_asian) + jobs
        + autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.01630188586436264
                ave_income: -1.2300835983182983
                jobs: 0.0716467811034511
                np.log1p(asian * pct_asian): 3.0
                np.log1p(black * pct_black): 3.0
                np.log1p(hisp * pct_hisp): 3.0
                np.log1p(pct_renters): -0.10085922828141121
                np.log1p(residential_units): 0.053782841968058256
                np.log1p(unit_annual_rent / positive_income): 0.0006097796447645327
                np.log1p(white * pct_white): 3.0
            Std. Error:
                autoPeakTotal: 0.011685255962178318
                ave_income: 0.024494051056695183
                jobs: 0.006495603843850723
                np.log1p(asian * pct_asian): 0.006678391484159004
                np.log1p(black * pct_black): 0.007165605089022102
                np.log1p(hisp * pct_hisp): 0.0060560457272858656
                np.log1p(pct_renters): 0.06575936491197995
                np.log1p(residential_units): 0.005920720400918327
                np.log1p(unit_annual_rent / positive_income): 0.0027218693725449138
                np.log1p(white * pct_white): 0.005248645120743722
            T-Score:
                autoPeakTotal: 1.3950816239821338
                ave_income: -50.21968785282124
                jobs: 11.030041675228992
                np.log1p(asian * pct_asian): 449.209964272974
                np.log1p(black * pct_black): 418.6666670475714
                np.log1p(hisp * pct_hisp): 495.37274569829054
                np.log1p(pct_renters): -1.533762201268413
                np.log1p(residential_units): 9.083834115814069
                np.log1p(unit_annual_rent / positive_income): 0.22402972417239717
                np.log1p(white * pct_white): 571.5760793472938
        fitted: true
        log_likelihoods:
            convergence: -58770.704467591466
            'null': -62708.60242261291
            ratio: 0.06279677433221542
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.047333142025136055
                ave_income: -0.6193048292362323
                jobs: 0.04634475491928613
                np.log1p(asian * pct_asian): 3.0
                np.log1p(black * pct_black): 3.0
                np.log1p(hisp * pct_hisp): 3.0
                np.log1p(pct_renters): -0.022279342110117367
                np.log1p(residential_units): 0.06604493909140717
                np.log1p(unit_annual_rent / positive_income): -0.03283477434936271
                np.log1p(white * pct_white): 3.0
            Std. Error:
                autoPeakTotal: 0.01259879013403566
                ave_income: 0.022273725906719638
                jobs: 0.0064538659667188625
                np.log1p(asian * pct_asian): 0.007816633833496378
                np.log1p(black * pct_black): 0.008596020761082832
                np.log1p(hisp * pct_hisp): 0.005707196873238288
                np.log1p(pct_renters): 0.05922202653474781
                np.log1p(residential_units): 0.005745506671719771
                np.log1p(unit_annual_rent / positive_income): 0.019172235696013878
                np.log1p(white * pct_white): 0.006344775198947493
            T-Score:
                autoPeakTotal: 3.7569593208212484
                ave_income: -27.804276295300806
                jobs: 7.1809292536094835
                np.log1p(asian * pct_asian): 383.79692127117346
                np.log1p(black * pct_black): 348.9986917646873
                np.log1p(hisp * pct_hisp): 525.6520962273704
                np.log1p(pct_renters): -0.37620026557256075
                np.log1p(residential_units): 11.49505915927138
                np.log1p(unit_annual_rent / positive_income): -1.7126210458694406
                np.log1p(white * pct_white): 472.82999096605613
        fitted: true
        log_likelihoods:
            convergence: -65173.04619693782
            'null': -67778.89479738499
            ratio: 0.038446312945009886
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.20298491566842675
                ave_income: 0.14983800648628928
                jobs: 0.020261021631345806
                np.log1p(asian * pct_asian): 3.0
                np.log1p(black * pct_black): 3.0
                np.log1p(hisp * pct_hisp): 3.0
                np.log1p(pct_renters): -0.23546595812446963
                np.log1p(residential_units): 0.08163431394147083
                np.log1p(unit_annual_rent / positive_income): -0.08061499197459772
                np.log1p(white * pct_white): 3.0
            Std. Error:
                autoPeakTotal: 0.013642170028007957
                ave_income: 0.020839331626668716
                jobs: 0.006229000020689676
                np.log1p(asian * pct_asian): 0.008454171223200732
                np.log1p(black * pct_black): 0.010134751404347614
                np.log1p(hisp * pct_hisp): 0.006360933029346913
                np.log1p(pct_renters): 0.054569192734611395
                np.log1p(residential_units): 0.005716436895986178
                np.log1p(unit_annual_rent / positive_income): 0.02834217248369341
                np.log1p(white * pct_white): 0.0072832386198083835
            T-Score:
                autoPeakTotal: 14.87922487783762
                ave_income: 7.190154135967447
                jobs: 3.2526924970378315
                np.log1p(asian * pct_asian): 354.85441692582685
                np.log1p(black * pct_black): 296.01120740988847
                np.log1p(hisp * pct_hisp): 471.6289239580337
                np.log1p(pct_renters): -4.3149980112335715
                np.log1p(residential_units): 14.280628899934282
                np.log1p(unit_annual_rent / positive_income): -2.844347659692613
                np.log1p(white * pct_white): 411.90466996932304
        fitted: true
        log_likelihoods:
            convergence: -65991.74374637737
            'null': -67843.36717998875
            ratio: 0.02729262285433176
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.5239212521388005
                ave_income: 1.504359585236809
                jobs: 0.07417487358212581
                np.log1p(asian * pct_asian): 3.0
                np.log1p(black * pct_black): 3.0
                np.log1p(hisp * pct_hisp): 3.0
                np.log1p(pct_renters): -0.24778344390038104
                np.log1p(residential_units): 0.07099951956007357
                np.log1p(unit_annual_rent / positive_income): 0.03616115331387844
                np.log1p(white * pct_white): 3.0
            Std. Error:
                autoPeakTotal: 0.01511599883996884
                ave_income: 0.021653757765951527
                jobs: 0.006171288322155094
                np.log1p(asian * pct_asian): 0.00976072681387431
                np.log1p(black * pct_black): 0.012697884818965229
                np.log1p(hisp * pct_hisp): 0.007490198495535439
                np.log1p(pct_renters): 0.060481289198760654
                np.log1p(residential_units): 0.00605420883212734
                np.log1p(unit_annual_rent / positive_income): 0.04403255622750478
                np.log1p(white * pct_white): 0.008737749434977874
            T-Score:
                autoPeakTotal: 34.6600484483684
                ave_income: 69.4733727742291
                jobs: 12.019349884502395
                np.log1p(asian * pct_asian): 307.354160935605
                np.log1p(black * pct_black): 236.2598214404401
                np.log1p(hisp * pct_hisp): 400.5234309595615
                np.log1p(pct_renters): -4.096861148016972
                np.log1p(residential_units): 11.727299392664923
                np.log1p(unit_annual_rent / positive_income): 0.821236748714818
                np.log1p(white * pct_white): 343.33783800102714
        fitted: true
        log_likelihoods:
            convergence: -64092.72892815659
            'null': -67723.63275515319
            ratio: 0.05361354196877921
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
