name: !!python/unicode 'hlcmr'

model_type: !!python/unicode 'segmented_locationchoice'

segmentation_col: !!python/unicode 'income_quartile'

choosers_fit_filters:
- !!python/unicode 'tenure == 1'

choosers_predict_filters:
- !!python/unicode 'tenure == 1'

alts_fit_filters:
- !!python/unicode 'general_type == ''Residential'''

alts_predict_filters:
- !!python/unicode 'general_type == ''Residential'''

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 5000

default_config:
    !!python/unicode 'model_expression': !!python/unicode 'np.log1p(residential_rent)
        + np.log1p(unit_sqft) + sum_residential_units + ave_unit_sqft + ave_lot_sqft
        + ave_income + hhsize + jobs + sfdu + renters + poor - 1'

models:
    !!python/unicode '0':
        !!python/unicode 'fit_parameters':
            !!python/unicode 'Coefficient':
                !!python/unicode 'ave_income': 0.8309100117610811
                !!python/unicode 'ave_lot_sqft': 0.17976141465787668
                !!python/unicode 'ave_unit_sqft': 0.49808164106825936
                !!python/unicode 'hhsize': -2.375467980921946
                !!python/unicode 'jobs': -0.00010113317597198293
                !!python/unicode 'np.log1p(residential_rent)': -3
                !!python/unicode 'np.log1p(unit_sqft)': -1.3077461396708654
                !!python/unicode 'poor': 1.6656715049562256
                !!python/unicode 'renters': -1.02712887167257
                !!python/unicode 'sfdu': -0.037546216385202134
                !!python/unicode 'sum_residential_units': -0.28462767185298493
            !!python/unicode 'Std. Error':
                !!python/unicode 'ave_income': 0.08663916963406768
                !!python/unicode 'ave_lot_sqft': 0.023061457021310225
                !!python/unicode 'ave_unit_sqft': 0.03506463960335656
                !!python/unicode 'hhsize': 0.1422347618299919
                !!python/unicode 'jobs': 0.016926598100655003
                !!python/unicode 'np.log1p(residential_rent)': 0.4467682488836038
                !!python/unicode 'np.log1p(unit_sqft)': 0.06913165322461759
                !!python/unicode 'poor': 0.05393113762521722
                !!python/unicode 'renters': 0.031152802462397395
                !!python/unicode 'sfdu': 0.011614526215217474
                !!python/unicode 'sum_residential_units': 0.05719949651344551
            !!python/unicode 'T-Score':
                !!python/unicode 'ave_income': 9.590466012896277
                !!python/unicode 'ave_lot_sqft': 7.794885400855892
                !!python/unicode 'ave_unit_sqft': 14.204670194887175
                !!python/unicode 'hhsize': -16.701036725194207
                !!python/unicode 'jobs': -0.005974808131591983
                !!python/unicode 'np.log1p(residential_rent)': -6.714890790687294
                !!python/unicode 'np.log1p(unit_sqft)': -18.91674911088602
                !!python/unicode 'poor': 30.88515425970521
                !!python/unicode 'renters': -32.970673277704414
                !!python/unicode 'sfdu': -3.232694617883654
                !!python/unicode 'sum_residential_units': -4.976052049445564
        !!python/unicode 'fitted': true
        !!python/unicode 'log_likelihoods':
            !!python/unicode 'convergence': -17311.70813270752
            !!python/unicode 'null': -22869.27514361628
            !!python/unicode 'ratio': 0.24301456762437423
        !!python/unicode 'name': 0
    !!python/unicode '1':
        !!python/unicode 'fit_parameters':
            !!python/unicode 'Coefficient':
                !!python/unicode 'ave_income': 0.8735027491005923
                !!python/unicode 'ave_lot_sqft': 0.18356857113560046
                !!python/unicode 'ave_unit_sqft': 0.36616756872180883
                !!python/unicode 'hhsize': -1.1808497400270443
                !!python/unicode 'jobs': -0.082662991823567
                !!python/unicode 'np.log1p(residential_rent)': -3
                !!python/unicode 'np.log1p(unit_sqft)': -1.251595216895387
                !!python/unicode 'poor': 0.8820647496472506
                !!python/unicode 'renters': -1.051528986288323
                !!python/unicode 'sfdu': -0.04321987421436481
                !!python/unicode 'sum_residential_units': 0.641352004749979
            !!python/unicode 'Std. Error':
                !!python/unicode 'ave_income': 0.0861481881051478
                !!python/unicode 'ave_lot_sqft': 0.022613229946665293
                !!python/unicode 'ave_unit_sqft': 0.035579675353544844
                !!python/unicode 'hhsize': 0.13415985626631036
                !!python/unicode 'jobs': 0.016814419061652444
                !!python/unicode 'np.log1p(residential_rent)': 0.45591218240351594
                !!python/unicode 'np.log1p(unit_sqft)': 0.07047283001201604
                !!python/unicode 'poor': 0.04796435895197188
                !!python/unicode 'renters': 0.02886594083129606
                !!python/unicode 'sfdu': 0.011036196699541692
                !!python/unicode 'sum_residential_units': 0.05070865548100702
            !!python/unicode 'T-Score':
                !!python/unicode 'ave_income': 10.139537096641456
                !!python/unicode 'ave_lot_sqft': 8.117751049653602
                !!python/unicode 'ave_unit_sqft': 10.291481445047168
                !!python/unicode 'hhsize': -8.801811308466453
                !!python/unicode 'jobs': -4.9161967190464
                !!python/unicode 'np.log1p(residential_rent)': -6.580214602260351
                !!python/unicode 'np.log1p(unit_sqft)': -17.7599681562665
                !!python/unicode 'poor': 18.390003930428588
                !!python/unicode 'renters': -36.42801710271191
                !!python/unicode 'sfdu': -3.9161928145191207
                !!python/unicode 'sum_residential_units': 12.647781698534644
        !!python/unicode 'fitted': true
        !!python/unicode 'log_likelihoods':
            !!python/unicode 'convergence': -18602.32657094184
            !!python/unicode 'null': -22887.695824360228
            !!python/unicode 'ratio': 0.1872346297462285
        !!python/unicode 'name': 1
    !!python/unicode '2':
        !!python/unicode 'fit_parameters':
            !!python/unicode 'Coefficient':
                !!python/unicode 'ave_income': 1.6025286938712882
                !!python/unicode 'ave_lot_sqft': 0.17438776456767785
                !!python/unicode 'ave_unit_sqft': 0.23747352908654162
                !!python/unicode 'hhsize': -0.3228010960352187
                !!python/unicode 'jobs': -0.0852246821696905
                !!python/unicode 'np.log1p(residential_rent)': -3
                !!python/unicode 'np.log1p(unit_sqft)': -1.155097839188833
                !!python/unicode 'poor': 0.4778129398018274
                !!python/unicode 'renters': -1.0915443056943246
                !!python/unicode 'sfdu': -0.06170590354110704
                !!python/unicode 'sum_residential_units': 1.1813613506303282
            !!python/unicode 'Std. Error':
                !!python/unicode 'ave_income': 0.08532360926982353
                !!python/unicode 'ave_lot_sqft': 0.022174395681466237
                !!python/unicode 'ave_unit_sqft': 0.038931175887309245
                !!python/unicode 'hhsize': 0.12991754611155776
                !!python/unicode 'jobs': 0.017189593215921322
                !!python/unicode 'np.log1p(residential_rent)': 0.47195044034503264
                !!python/unicode 'np.log1p(unit_sqft)': 0.07283598827660853
                !!python/unicode 'poor': 0.04278888839589337
                !!python/unicode 'renters': 0.029206661586485265
                !!python/unicode 'sfdu': 0.01053603670701754
                !!python/unicode 'sum_residential_units': 0.04304112414914098
            !!python/unicode 'T-Score':
                !!python/unicode 'ave_income': 18.781773387053093
                !!python/unicode 'ave_lot_sqft': 7.864375069009629
                !!python/unicode 'ave_unit_sqft': 6.099829344326408
                !!python/unicode 'hhsize': -2.484661277069038
                !!python/unicode 'jobs': -4.957923151477128
                !!python/unicode 'np.log1p(residential_rent)': -6.356599641705527
                !!python/unicode 'np.log1p(unit_sqft)': -15.858888806480238
                !!python/unicode 'poor': 11.166752811640816
                !!python/unicode 'renters': -37.373128129077664
                !!python/unicode 'sfdu': -5.856652293172797
                !!python/unicode 'sum_residential_units': 27.447269883955993
        !!python/unicode 'fitted': true
        !!python/unicode 'log_likelihoods':
            !!python/unicode 'convergence': -19326.91834123438
            !!python/unicode 'null': -22850.854462872332
            !!python/unicode 'ratio': 0.15421463242714095
        !!python/unicode 'name': 2
    !!python/unicode '3':
        !!python/unicode 'fit_parameters':
            !!python/unicode 'Coefficient':
                !!python/unicode 'ave_income': 2.664351013087487
                !!python/unicode 'ave_lot_sqft': 0.16147963923755287
                !!python/unicode 'ave_unit_sqft': 0.1256642505805482
                !!python/unicode 'hhsize': -0.024189897748325504
                !!python/unicode 'jobs': -0.048763136943277295
                !!python/unicode 'np.log1p(residential_rent)': -2.36850691890878
                !!python/unicode 'np.log1p(unit_sqft)': -1.017246302103054
                !!python/unicode 'poor': 0.41671579092957983
                !!python/unicode 'renters': -1.0176828034099534
                !!python/unicode 'sfdu': -0.11694589815778902
                !!python/unicode 'sum_residential_units': 1.2644813639031507
            !!python/unicode 'Std. Error':
                !!python/unicode 'ave_income': 0.0935216145939036
                !!python/unicode 'ave_lot_sqft': 0.02263096113371971
                !!python/unicode 'ave_unit_sqft': 0.04468939001974972
                !!python/unicode 'hhsize': 0.13796727949399767
                !!python/unicode 'jobs': 0.018691794571835205
                !!python/unicode 'np.log1p(residential_rent)': 0.516674200198568
                !!python/unicode 'np.log1p(unit_sqft)': 0.08029258999312984
                !!python/unicode 'poor': 0.04571060028597525
                !!python/unicode 'renters': 0.03293412687888006
                !!python/unicode 'sfdu': 0.010205721939290055
                !!python/unicode 'sum_residential_units': 0.04427240661359798
            !!python/unicode 'T-Score':
                !!python/unicode 'ave_income': 28.489146863608237
                !!python/unicode 'ave_lot_sqft': 7.135341635886212
                !!python/unicode 'ave_unit_sqft': 2.811948216903677
                !!python/unicode 'hhsize': -0.1753306859209172
                !!python/unicode 'jobs': -2.6087991046484955
                !!python/unicode 'np.log1p(residential_rent)': -4.584140098341502
                !!python/unicode 'np.log1p(unit_sqft)': -12.669242606199324
                !!python/unicode 'poor': 9.11639287873091
                !!python/unicode 'renters': -30.900555133968687
                !!python/unicode 'sfdu': -11.458856007782256
                !!python/unicode 'sum_residential_units': 28.561387568995933
        !!python/unicode 'fitted': true
        !!python/unicode 'log_likelihoods':
            !!python/unicode 'convergence': -19063.165637532933
            !!python/unicode 'null': -22878.485483988254
            !!python/unicode 'ratio': 0.16676452858409319
        !!python/unicode 'name': 3

fitted: true

!!python/unicode 'desc': !!python/unicode 'Household Location Choice Model (Renter)'
