name: hlcm_renter

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 2

choosers_predict_filters:
- hownrent == 2

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 1

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + sum_residential_units + ave_income
        + autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.0014905376128616895
                ave_income: -0.8676624451050875
                np.log1p(residential_price): 0.02689063342193343
                sum_residential_units: 0.2653414581501586
            Std. Error:
                autoPeakTotal: 0.010477279494837951
                ave_income: 0.008090436499360552
                np.log1p(residential_price): 0.018888094373045148
                sum_residential_units: 0.009297801435297239
            T-Score:
                autoPeakTotal: 0.142263801743197
                ave_income: -107.24544283533594
                np.log1p(residential_price): 1.4236816531533514
                sum_residential_units: 28.53808612677433
        fitted: true
        log_likelihoods:
            convergence: -60268.555410495195
            'null': -62225.0595530839
            ratio: 0.031442382805911495
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.021711881135277826
                ave_income: -0.4992732206972286
                np.log1p(residential_price): -0.011363345303168732
                sum_residential_units: 0.21125965763166804
            Std. Error:
                autoPeakTotal: 0.012306168418354713
                ave_income: 0.01046365242551126
                np.log1p(residential_price): 0.020972687710200385
                sum_residential_units: 0.010024491907823358
            T-Score:
                autoPeakTotal: 1.7643087919140163
                ave_income: -47.715004321049385
                np.log1p(residential_price): -0.5418163594569712
                sum_residential_units: 21.074350657792028
        fitted: true
        log_likelihoods:
            convergence: -66483.66488947545
            'null': -67484.16390548206
            ratio: 0.014825685881029838
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.1748020824419429
                ave_income: 0.11321894815274186
                np.log1p(residential_price): 0.033428656542047075
                sum_residential_units: 0.14575405199084748
            Std. Error:
                autoPeakTotal: 0.014523273226489055
                ave_income: 0.013392677211756965
                np.log1p(residential_price): 0.022962645757873167
                sum_residential_units: 0.01059880958334766
            T-Score:
                autoPeakTotal: 12.035997651212723
                ave_income: 8.45379503758598
                np.log1p(residential_price): 1.455784185086139
                sum_residential_units: 13.75192665220151
        fitted: true
        log_likelihoods:
            convergence: -67163.68398277217
            'null': -67728.23792533917
            ratio: 0.00833557700392773
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.4141407720764638
                ave_income: 1.4473327587675102
                np.log1p(residential_price): 0.15001990259133524
                sum_residential_units: 0.22776072360660238
            Std. Error:
                autoPeakTotal: 0.016048129138786758
                ave_income: 0.014765677907085082
                np.log1p(residential_price): 0.023603014237898012
                sum_residential_units: 0.010425496797754367
            T-Score:
                autoPeakTotal: 25.806171454311524
                ave_income: 98.02006842320662
                np.log1p(residential_price): 6.355963737481328
                sum_residential_units: 21.846510341421965
        fitted: true
        log_likelihoods:
            convergence: -64807.187906640145
            'null': -67622.31901106155
            ratio: 0.04163020649973437
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
