name: hlcm_owner

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 1

choosers_predict_filters:
- hownrent == 1

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 1500

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + poor + jobs - 1

models:
    1:
        fit_parameters:
            Coefficient:
                jobs: -0.053837349841079726
                np.log1p(residential_price): 0.5645767370572821
                poor: 0.24425591444899308
            Std. Error:
                jobs: 0.020533594315989525
                np.log1p(residential_price): 0.023253457418315998
                poor: 0.029593989704142346
            T-Score:
                jobs: -2.621915530840918
                np.log1p(residential_price): 24.279259935453005
                poor: 8.253564892428274
        fitted: true
        log_likelihoods:
            convergence: -6613.9182607584125
            'null': -6778.810513774412
            ratio: 0.02432465882929491
        name: 1
    2:
        fit_parameters:
            Coefficient:
                jobs: -0.01849296958374711
                np.log1p(residential_price): 0.643685075136904
                poor: 0.1603757892082461
            Std. Error:
                jobs: 0.020411911297494357
                np.log1p(residential_price): 0.02268661153669964
                poor: 0.02918668464115026
            T-Score:
                jobs: -0.9059891214605267
                np.log1p(residential_price): 28.372905054403063
                poor: 5.4948272193318095
        fitted: true
        log_likelihoods:
            convergence: -6654.961014801893
            'null': -6815.651875262315
            ratio: 0.023576741212921415
        name: 2
    3:
        fit_parameters:
            Coefficient:
                jobs: -0.03428802020020741
                np.log1p(residential_price): 0.6020793891716559
                poor: 0.08282008968838304
            Std. Error:
                jobs: 0.019041657800596447
                np.log1p(residential_price): 0.02307662270731873
                poor: 0.028721903074311203
            T-Score:
                jobs: -1.8006846126146325
                np.log1p(residential_price): 26.090446457778548
                poor: 2.883516787662205
        fitted: true
        log_likelihoods:
            convergence: -6692.739826280589
            'null': -6820.257045448303
            ratio: 0.018696834784667882
        name: 3
    4:
        fit_parameters:
            Coefficient:
                jobs: 0.09921819688848951
                np.log1p(residential_price): 1.0232342645814532
                poor: -0.26573088911042725
            Std. Error:
                jobs: 0.01889024654597475
                np.log1p(residential_price): 0.0173738841384811
                poor: 0.02445558656513962
            T-Score:
                jobs: 5.252350552811156
                np.log1p(residential_price): 58.89496306212323
                poor: -10.865856290243928
        fitted: true
        log_likelihoods:
            convergence: -6574.72603391768
            'null': -6834.0725560062665
            ratio: 0.03794904428701951
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
