name: Household Location Choice Model (RENTERS)

model_type: locationchoice

choosers_fit_filters:
- tenure == 1

choosers_predict_filters:
- tenure == 1

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 5000

model_expression: np.log1p(residential_rent) + np.log1p(unit_sqft) + sum_residential_units
    + ave_unit_sqft + ave_lot_sqft + ave_income - 1

fitted: true

log_likelihoods:
    convergence: -19443.26613945041
    'null': -22846.249292686345
    ratio: 0.14895150226366982

fit_parameters:
    Coefficient:
        ave_income: -0.44562537768215205
        ave_lot_sqft: -0.00426566866402967
        ave_unit_sqft: 1.20998139514279
        np.log1p(residential_rent): -3.0
        np.log1p(unit_sqft): -1.4852006288345339
        sum_residential_units: 0.8870625744016138
    Std. Error:
        ave_income: 0.032622069701731475
        ave_lot_sqft: 0.005144019695447223
        ave_unit_sqft: 0.0646580193230628
        np.log1p(residential_rent): 0.2690081849488403
        np.log1p(unit_sqft): 0.04487432319255651
        sum_residential_units: 0.02056401634050805
    T-Score:
        ave_income: -13.66024233767423
        ave_lot_sqft: -0.829248120454331
        ave_unit_sqft: 18.713554912610864
        np.log1p(residential_rent): -11.152077029070831
        np.log1p(unit_sqft): -33.096892012421264
        sum_residential_units: 43.136640222087
