name: hlcm_renter

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 2

choosers_predict_filters:
- hownrent == 2

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 1

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 1500

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + sum_residential_units + ave_income
        + autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.19648902804202875
                ave_income: -0.7407474872688148
                np.log1p(residential_price): 1.1649368451780786
                sum_residential_units: 0.133884565547746
            Std. Error:
                autoPeakTotal: 0.03806651769358313
                ave_income: 0.04530936152788033
                np.log1p(residential_price): 0.09484851616522018
                sum_residential_units: 0.03290386184486277
            T-Score:
                autoPeakTotal: -5.1617284676173805
                ave_income: -16.34866310824108
                np.log1p(residential_price): 12.282077699020947
                sum_residential_units: 4.068962062234321
        fitted: true
        log_likelihoods:
            convergence: -6629.252543680403
            'null': -6847.88806656423
            ratio: 0.031927438176354794
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.18053183430609138
                ave_income: -0.674345440078151
                np.log1p(residential_price): 1.1166872128222924
                sum_residential_units: 0.11066995409764457
            Std. Error:
                autoPeakTotal: 0.03826675014388765
                ave_income: 0.04198814043621757
                np.log1p(residential_price): 0.0886344177431236
                sum_residential_units: 0.032311475345547624
            T-Score:
                autoPeakTotal: -4.717720570136468
                ave_income: -16.06037878963754
                np.log1p(residential_price): 12.598798990913739
                sum_residential_units: 3.425097520744883
        fitted: true
        log_likelihoods:
            convergence: -6611.660259440564
            'null': -6815.651875262315
            ratio: 0.029929876049295756
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.16865609618895072
                ave_income: -0.22131283902188464
                np.log1p(residential_price): 0.5754969474264675
                sum_residential_units: 0.0738794783520498
            Std. Error:
                autoPeakTotal: 0.039655443252615406
                ave_income: 0.04614480618527415
                np.log1p(residential_price): 0.10124933799927645
                sum_residential_units: 0.033921591312732924
            T-Score:
                autoPeakTotal: -4.253037725856899
                ave_income: -4.796050895377053
                np.log1p(residential_price): 5.683957631708961
                sum_residential_units: 2.1779484833401126
        fitted: true
        log_likelihoods:
            convergence: -6712.4835595598315
            'null': -6834.0725560062665
            ratio: 0.017791587000283493
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: -0.09120873955012335
                ave_income: 1.0640964935076667
                np.log1p(residential_price): 0.859425253161156
                sum_residential_units: 0.09496352911258277
            Std. Error:
                autoPeakTotal: 0.042611885540911616
                ave_income: 0.04728340947636341
                np.log1p(residential_price): 0.10105670071027195
                sum_residential_units: 0.03110770056141066
            T-Score:
                autoPeakTotal: -2.1404530307055754
                ave_income: 22.504648148090922
                np.log1p(residential_price): 8.504386617816817
                sum_residential_units: 3.052733805416198
        fitted: true
        log_likelihoods:
            convergence: -6528.004017070545
            'null': -6797.231194518364
            ratio: 0.039608359601618015
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
