name: hlcm_renter

model_type: segmented_discretechoice

segmentation_col: income_quartile

choosers_fit_filters:
- hownrent == 2

choosers_predict_filters:
- hownrent == 2

alts_fit_filters: null

alts_predict_filters:
- unit_tenure == 1

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(residential_price) + sum_residential_units + ave_income
        + autoPeakTotal - 1

models:
    1:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.02918867021548129
                ave_income: -0.92041152578117
                np.log1p(residential_price): -0.12740576580092536
                sum_residential_units: 0.26302550688110876
            Std. Error:
                autoPeakTotal: 0.01306119092397992
                ave_income: 0.007806874391535227
                np.log1p(residential_price): 0.023330337643612968
                sum_residential_units: 0.009090626238847682
            T-Score:
                autoPeakTotal: 2.234763306452541
                ave_income: -117.89757073319204
                np.log1p(residential_price): -5.460948218887205
                sum_residential_units: 28.93370599234422
        fitted: true
        log_likelihoods:
            convergence: -60926.9829153358
            'null': -62952.67644247041
            ratio: 0.03217803660795582
        name: 1
    2:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.06181390078065625
                ave_income: -0.4604083576836908
                np.log1p(residential_price): -0.13778602700558537
                sum_residential_units: 0.21189345340532412
            Std. Error:
                autoPeakTotal: 0.014032603183025013
                ave_income: 0.011785308009118003
                np.log1p(residential_price): 0.027368086931997847
                sum_residential_units: 0.01005938076937428
            T-Score:
                autoPeakTotal: 4.405020221439128
                ave_income: -39.06629825266206
                np.log1p(residential_price): -5.034550911356927
                sum_residential_units: 21.06426411956016
        fitted: true
        log_likelihoods:
            convergence: -66794.72293281296
            'null': -67769.68445701302
            ratio: 0.014386396100434684
        name: 2
    3:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.18317672500961907
                ave_income: 0.1056142446391218
                np.log1p(residential_price): 0.05677790230258906
                sum_residential_units: 0.13317950259317848
            Std. Error:
                autoPeakTotal: 0.014927769335756565
                ave_income: 0.01547858372113332
                np.log1p(residential_price): 0.031338640235995106
                sum_residential_units: 0.010694767852090838
            T-Score:
                autoPeakTotal: 12.27087054265066
                ave_income: 6.823249887838502
                np.log1p(residential_price): 1.8117538564221045
                sum_residential_units: 12.45277171370688
        fitted: true
        log_likelihoods:
            convergence: -67154.13804536998
            'null': -67700.60690422327
            ratio: 0.008071845790487253
        name: 3
    4:
        fit_parameters:
            Coefficient:
                autoPeakTotal: 0.373687666776667
                ave_income: 1.4799213148634325
                np.log1p(residential_price): 0.24734246468419582
                sum_residential_units: 0.25495831970963534
            Std. Error:
                autoPeakTotal: 0.016123546865574663
                ave_income: 0.016089716166208762
                np.log1p(residential_price): 0.030939663206837456
                sum_residential_units: 0.010116696984993344
            T-Score:
                autoPeakTotal: 23.17651754245999
                ave_income: 91.97933012463749
                np.log1p(residential_price): 7.994348969821197
                sum_residential_units: 25.201735318140805
        fitted: true
        log_likelihoods:
            convergence: -64687.72918776812
            'null': -67599.29316013164
            ratio: 0.043070923322622634
        name: 4

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
