name: Household Location Choice Model

model_type: locationchoice

choosers_fit_filters:
- tenure == 1

choosers_predict_filters:
- tenure == 1

sample_size: 100

estimation_sample_size: 5000

model_expression: np.log1p(residential_rent) + np.log1p(unit_sqft) + sum_residential_units
    + ave_unit_sqft + ave_lot_sqft + ave_income - 1

location_id_col: building_id

coefficients:
- 3.0
- -1.0303220158138735
- 0.7605723325781093
- 1.0061718094697825
- 0.5075714905850593
- -0.36795218533700813

fitted: true

