model_configs:
  hlcm:
    hlcm_owner_config: hlcm_owner.yaml
    hlcm_owner_lowincome_config: hlcm_owner_lowincome.yaml
    hlcm_owner_no_unplaced_config: hlcm_owner_no_unplaced.yaml
    hlcm_owner_lowincome_no_unplaced_config: hlcm_owner_lowincome_no_unplaced.yaml
    hlcm_renter_config: hlcm_renter.yaml
    hlcm_renter_lowincome_config: hlcm_renter_lowincome.yaml
    hlcm_renter_no_unplaced_config: hlcm_renter_no_unplaced.yaml
    hlcm_renter_lowincome_no_unplaced_config: hlcm_renter_lowincome_no_unplaced.yaml
  elcm:
    elcm_config: elcm.yaml
  rsh:
    rsh_config: rsh.yaml
    s1_rsh_config: rsh_s1.yaml
    s2_rsh_config: rsh_s2.yaml
    s5_rsh_config: rsh_s5.yaml
    s6_rsh_config: rsh_s1.yaml
    s7_rsh_config: rsh_s2.yaml
    s10_rsh_config: rsh_s5.yaml
    s11_rsh_config: rsh_s1.yaml
    s12_rsh_config: rsh_s2.yaml
    s15_rsh_config: rsh_s5.yaml
  rrh:
    rrh_config: rrh.yaml
  nrh:
    nrh_config: nrh.yaml