control_tables:
  household:
    household_controls_input_file: household_controls.csv
    s1_household_controls_input_file: household_controls_s1.csv
    s2_household_controls_input_file: household_controls_s2.csv
    s5_household_controls_input_file: household_controls_s5.csv
    s6_household_controls_input_file: household_controls_s6.csv
    s7_household_controls_input_file: household_controls_s7.csv
    s10_household_controls_input_file: household_controls_s10.csv
    s11_household_controls_input_file: household_controls_s11.csv
    s12_household_controls_input_file: household_controls_s12.csv
    s15_household_controls_input_file: household_controls_s15.csv
    s16_household_controls_input_file: household_controls_s16.csv
    s21_household_controls_input_file: household_controls_s21.csv
    s17_household_controls_input_file: household_controls_s17.csv
    s22_household_controls_input_file: household_controls_s22.csv
    s23_household_controls_input_file: household_controls_s23.csv
    s24_household_controls_input_file: household_controls_s24.csv
    s25_household_controls_input_file: household_controls_s25.csv
    s20_household_controls_input_file: household_controls_s20.csv
    s26_household_controls_input_file: household_controls_s26.csv
    s27_household_controls_input_file: household_controls_s27.csv
    s28_household_controls_input_file: household_controls_s28.csv
    s29_household_controls_input_file: household_controls_s29.csv
  employment:
    employment_controls_input_file: employment_controls.csv
    s1_employment_controls_input_file: employment_controls_s1.csv
    s2_employment_controls_input_file: employment_controls_s2.csv
    s5_employment_controls_input_file: employment_controls_s5.csv
    s6_employment_controls_input_file: employment_controls_s6.csv
    s7_employment_controls_input_file: employment_controls_s7.csv
    s10_employment_controls_input_file: employment_controls_s10.csv
    s11_employment_controls_input_file: employment_controls_s11.csv
    s12_employment_controls_input_file: employment_controls_s12.csv
    s15_employment_controls_input_file: employment_controls_s15.csv
    s21_employment_controls_input_file: employment_controls_s21.csv
    s22_employment_controls_input_file: employment_controls_s22.csv
    s23_employment_controls_input_file: employment_controls_s23.csv
    s24_employment_controls_input_file: employment_controls_s24.csv
    s25_employment_controls_input_file: employment_controls_s25.csv
    s20_employment_controls_input_file: employment_controls_s20.csv
    s26_employment_controls_input_file: employment_controls_s26.csv
    s27_employment_controls_input_file: employment_controls_s27.csv
    s28_employment_controls_input_file: employment_controls_s28.csv
    s29_employment_controls_input_file: employment_controls_s29.csv
  regional:
    regional_controls_input_file: regional_controls.csv
    s1_regional_controls_input_file: regional_controls_s1.csv
    s2_regional_controls_input_file: regional_controls_s2.csv
    s5_regional_controls_input_file: regional_controls_s5.csv
    s6_regional_controls_input_file: regional_controls_s6.csv
    s7_regional_controls_input_file: regional_controls_s7.csv
    s10_regional_controls_input_file: regional_controls_s10.csv
    s11_regional_controls_input_file: regional_controls_s11.csv
    s12_regional_controls_input_file: regional_controls_s12.csv
    s15_regional_controls_input_file: regional_controls_s15.csv
    s16_regional_controls_input_file: regional_controls_s16.csv
    s17_regional_controls_input_file: regional_controls_s17.csv
    s21_regional_controls_input_file: regional_controls_s21.csv
    s22_regional_controls_input_file: regional_controls_s22.csv
    s23_regional_controls_input_file: regional_controls_s23.csv
    s24_regional_controls_input_file: regional_controls_s24.csv
    s25_regional_controls_input_file: regional_controls_s25.csv
    s20_regional_controls_input_file: regional_controls_s20.csv
    s26_regional_controls_input_file: regional_controls_s26.csv
    s27_regional_controls_input_file: regional_controls_s27.csv
    s28_regional_controls_input_file: regional_controls_s28.csv
    s29_regional_controls_input_file: regional_controls_s29.csv
  demographic_forecast:
    demographic_forecast_controls_input_file: regional_demographic_forecast.csv
    s1_demographic_forecast_controls_input_file: regional_demographic_forecast_s1.csv
    s2_demographic_forecast_controls_input_file: regional_demographic_forecast_s2.csv
    s5_demographic_forecast_controls_input_file: regional_demographic_forecast_s5.csv
    s6_demographic_forecast_controls_input_file: regional_demographic_forecast_s6.csv
    s7_demographic_forecast_controls_input_file: regional_demographic_forecast_s7.csv
    s10_demographic_forecast_controls_input_file: regional_demographic_forecast_s10.csv
    s11_demographic_forecast_controls_input_file: regional_demographic_forecast_s11.csv
    s12_demographic_forecast_controls_input_file: regional_demographic_forecast_s12.csv
    s15_demographic_forecast_controls_input_file: regional_demographic_forecast_s15.csv
    s21_demographic_forecast_controls_input_file: regional_demographic_forecast_s21.csv
    s22_demographic_forecast_controls_input_file: regional_demographic_forecast_s22.csv
    s23_demographic_forecast_controls_input_file: regional_demographic_forecast_s23.csv
    s24_demographic_forecast_controls_input_file: regional_demographic_forecast_s24.csv
    s25_demographic_forecast_controls_input_file: regional_demographic_forecast_s25.csv
    s20_demographic_forecast_controls_input_file: regional_demographic_forecast_s20.csv
    s26_demographic_forecast_controls_input_file: regional_demographic_forecast_s26.csv
    s27_demographic_forecast_controls_input_file: regional_demographic_forecast_s27.csv
    s28_demographic_forecast_controls_input_file: regional_demographic_forecast_s28.csv
    s29_demographic_forecast_controls_input_file: regional_demographic_forecast_s29.csv

model_configs:
  hlcm:
    hlcm_owner_config: hlcm_owner.yaml
    hlcm_owner_lowincome_config: hlcm_owner_lowincome.yaml
    hlcm_owner_no_unplaced_config: hlcm_owner_no_unplaced.yaml
    hlcm_owner_lowincome_no_unplaced_config: hlcm_owner_lowincome_no_unplaced.yaml
    hlcm_renter_config: hlcm_renter.yaml
    hlcm_renter_lowincome_config: hlcm_renter_lowincome.yaml
    hlcm_renter_no_unplaced_config: hlcm_renter_no_unplaced.yaml
    hlcm_renter_lowincome_no_unplaced_config: hlcm_renter_lowincome_no_unplaced.yaml
  elcm:
    elcm_config: elcm.yaml
  rsh:
    rsh_config: rsh.yaml
    s1_rsh_config: rsh_s1.yaml
    s2_rsh_config: rsh_s2.yaml
    s5_rsh_config: rsh_s5.yaml
    s6_rsh_config: rsh_s1.yaml
    s7_rsh_config: rsh_s2.yaml
    s10_rsh_config: rsh_s5.yaml
    s11_rsh_config: rsh_s1.yaml
    s12_rsh_config: rsh_s2.yaml
    s15_rsh_config: rsh_s5.yaml
  rrh:
    rrh_config: rrh.yaml
  nrh:
    nrh_config: nrh.yaml