name: !!python/unicode 'networks2'

model_type: !!python/unicode 'networks'

!!python/unicode 'desc': !!python/unicode 'Neighborhood Price Variables'

!!python/unicode 'variable_definitions':
-   !!python/unicode 'aggregation': !!python/unicode 'average'
    !!python/unicode 'dataframe': !!python/unicode 'buildings'
    !!python/unicode 'decay': !!python/unicode 'flat'
    !!python/unicode 'name': !!python/unicode 'residential'
    !!python/unicode 'radius': 2000
    !!python/unicode 'varname': !!python/unicode 'residential_sales_price'
-   !!python/unicode 'add_fields':
    - !!python/unicode 'general_type'
    !!python/unicode 'aggregation': !!python/unicode 'average'
    !!python/unicode 'dataframe': !!python/unicode 'buildings'
    !!python/unicode 'decay': !!python/unicode 'flat'
    !!python/unicode 'filters':
    - !!python/unicode 'general_type == "Retail"'
    !!python/unicode 'name': !!python/unicode 'retail'
    !!python/unicode 'radius': 2000
    !!python/unicode 'varname': !!python/unicode 'non_residential_rent'
-   !!python/unicode 'add_fields':
    - !!python/unicode 'general_type'
    !!python/unicode 'aggregation': !!python/unicode 'average'
    !!python/unicode 'dataframe': !!python/unicode 'buildings'
    !!python/unicode 'decay': !!python/unicode 'flat'
    !!python/unicode 'filters':
    - !!python/unicode 'general_type == "Office"'
    !!python/unicode 'name': !!python/unicode 'office'
    !!python/unicode 'radius': 2000
    !!python/unicode 'varname': !!python/unicode 'non_residential_rent'
-   !!python/unicode 'add_fields':
    - !!python/unicode 'general_type'
    !!python/unicode 'aggregation': !!python/unicode 'average'
    !!python/unicode 'dataframe': !!python/unicode 'buildings'
    !!python/unicode 'decay': !!python/unicode 'flat'
    !!python/unicode 'filters':
    - !!python/unicode 'general_type == "Industrial"'
    !!python/unicode 'name': !!python/unicode 'industrial'
    !!python/unicode 'radius': 2000
    !!python/unicode 'varname': !!python/unicode 'non_residential_rent'

!!python/unicode 'node_col': !!python/unicode '_node_id0'
