name: Neighborhood Price Variables

model_type: networks

variable_definitions:
-   aggregation: average
    dataframe: buildings
    decay: flat
    name: residential
    radius: 1500
    varname: residential_sales_price
-   aggregation: average
    dataframe: buildings
    decay: flat
    filters:
    - general_type == "Retail"
    name: retail
    radius: 1500
    varname: non_residential_rent
-   aggregation: average
    dataframe: buildings
    decay: flat
    filters:
    - general_type == "Office"
    name: office
    radius: 1500
    varname: non_residential_rent
-   aggregation: average
    dataframe: buildings
    decay: flat
    filters:
    - general_type == "Industrial"
    name: industrial
    radius: 1500
    varname: non_residential_rent
