name: Non-residential Rent Hedonic

model_type: regression

fit_filters: null

predict_filters: null

model_expression: np.log1p(averageweightedrent) ~ I(year_built < 1940) + I(year_built
    > 2005) + np.log1p(stories) + ave_income + jobs

ytransform: np.exp

fitted: true

coefficients:
    I(year_built < 1940)[T.True]: 0.1419647273961402
    I(year_built > 2005)[T.True]: 0.2474050610416706
    Intercept: 2.0783083213130404
    ave_income: 0.023323574020821556
    jobs: -0.0042417009652571894
    np.log1p(stories): 0.504259845374617

