name: Non-residential Rent Hedonic

model_type: regression

fit_filters: null

predict_filters: null

model_expression: np.log1p(averageweightedrent) ~ I(year_built < 1940) + I(year_built
    > 2005) + np.log1p(stories) + ave_income + jobs

ytransform: np.exp

coefficients:
    I(year_built < 1940)[T.True]: 0.14196472687259806
    I(year_built > 2005)[T.True]: 0.24740506156271963
    Intercept: 2.0783083189418092
    ave_income: 0.023323574093609613
    jobs: -0.004241700808085506
    np.log1p(stories): 0.5042598458207305

fitted: true
