name: Non-residential Rent Hedonic

model_type: regression

fit_filters: null

predict_filters: null

model_expression: np.log1p(averageweightedrent) ~ I(year_built < 1940) + I(year_built
    > 2005) + np.log1p(stories) + ave_income + jobs

ytransform: np.exp

    I(year_built < 1940)[T.True]: 0.14073273966377525
    I(year_built > 2005)[T.True]: 0.26696739612182596
    Intercept: 2.0206147348880616
    ave_income: 0.02152717282078399
    jobs: 0.004533460502513721
    np.log1p(stories): 0.48931059128029053

fitted: true
