# location of the hdf store
store: basis_inputs/parcels_buildings_agents/2015_09_01_bayarea_v3.h5

# large baus files are stored in s3 - this key gives the settings for fetching them
s3_settings:
  bucket: bayarea_urbansim
  files:
    - 2015_09_01_bayarea_v3.h5
    - 2015_06_01_osm_bayarea4326.h5
    - 2015_12_21_zoning_parcels.csv
    - 02_01_2016_parcels_geography.csv
    - 2015_08_29_costar.csv
    - 2015_08_03_tmnet.h5