# where to get the accessibliity networks
build_networks:
  walk:
      name: 2015_06_01_osm_bayarea4326.h5
      max_distance: 3000
  drive:
      name: 2015_08_03_tmnet.h5
      max_distance: 45
      weight_col: "CTIMEA"

# these are the tables that get auto-merged to buildings/parcels in the hedonic and lcms
aggregation_tables:
  - nodes
  - tmnodes
  - logsums
  - buildings

# clip the prices that come out of the sales hedonic
rsh_simulate:
  low: 200
  high: 2000

# price and rent equilibration, treated separately
price_equilibration:
  price_col: unit_residential_price
  submarket_col: submarket_id
  submarket_table: zones
  warm_start: False
  multiplier_func: supply_and_demand_multiplier_func
  clip_final_price_low: null
  clip_final_price_high: null
  kwargs:
    clip_change_low: 1.0
    clip_change_high: 1.2
    iterations: 8

rent_equilibration:
  price_col: unit_residential_rent
  submarket_col: submarket_id
  submarket_table: zones
  warm_start: False
  multiplier_func: supply_and_demand_multiplier_func
  clip_final_price_low: null
  clip_final_price_high: null
  kwargs:
    clip_change_low: 1.0
    clip_change_high: 1.2
    iterations: 8