name: networks2

desc: Neighborhood Price Variables

model_type: networks

node_col: node_id

variable_definitions:

-   aggregation: average
    dataframe: buildings
    decay: flat
    varname: residential_price
    radius: 2000
    name: residential

-   aggregation: average
    dataframe: buildings
    decay: flat
    filters:
    - general_type == "Retail"
    name: retail
    radius: 2000
    varname: non_residential_price

-   aggregation: average
    dataframe: buildings
    decay: flat
    filters:
    - general_type == "Office"
    name: office
    radius: 2000
    varname: non_residential_price

-   aggregation: average
    dataframe: buildings
    decay: flat
    filters:
    - general_type == "Industrial"
    name: industrial
    radius: 2000
    varname: non_residential_price
