name: networks

desc: Regional Accessibility Variables

model_type: networks

node_col: tmnode_id

variable_definitions:
    
  - name: residential_units_45
    dataframe: buildings
    varname: residential_units
    radius: 45
    apply: np.log1p

  - name: population_45
    filters:
    - building_id != -1
    dataframe: households
    varname: persons
    radius: 45
    apply: np.log1p
  
  - name: jobs_15
    filters:
    - building_id != -1
    dataframe: jobs
    radius: 15
    apply: np.log1p

  - name: jobs_45
    filters:
    - building_id != -1
    dataframe: jobs
    radius: 45
    apply: np.log1p
