name: !!python/unicode 'rrh'

model_type: !!python/unicode 'regression'

fit_filters: null

predict_filters:
- !!python/unicode 'general_type == ''Residential'''

model_expression: !!python/unicode 'np.log1p(rent) ~ np.log1p(unit_sqft) + sum_residential_units
    + ave_unit_sqft + ave_lot_sqft + jobs'

ytransform: !!python/unicode 'np.exp'

fitted: true

!!python/unicode 'fit_rsquared_adj': 0.24094338287499328

!!python/unicode 'fit_rsquared': 0.24182662306247882

!!python/unicode 'fit_parameters':
    !!python/unicode 'Coefficient':
        !!python/unicode 'Intercept': 2.206209634316291
        !!python/unicode 'ave_lot_sqft': 0.008925052599655234
        !!python/unicode 'ave_unit_sqft': -0.022773303472522925
        !!python/unicode 'jobs': 0.0306638484352557
        !!python/unicode 'np.log1p(unit_sqft)': -0.19928474256125667
        !!python/unicode 'sum_residential_units': 0.021582730966257353
    !!python/unicode 'Std. Error':
        !!python/unicode 'Intercept': 0.06306125025931283
        !!python/unicode 'ave_lot_sqft': 0.0027131867881994877
        !!python/unicode 'ave_unit_sqft': 0.00374204222812317
        !!python/unicode 'jobs': 0.0014662396346901466
        !!python/unicode 'np.log1p(unit_sqft)': 0.007761483734639144
        !!python/unicode 'sum_residential_units': 0.0029674545591622057
    !!python/unicode 'T-Score':
        !!python/unicode 'Intercept': 34.98518702442757
        !!python/unicode 'ave_lot_sqft': 3.289509088896174
        !!python/unicode 'ave_unit_sqft': -6.085795425121359
        !!python/unicode 'jobs': 20.913258453646797
        !!python/unicode 'np.log1p(unit_sqft)': -25.67611417799641
        !!python/unicode 'sum_residential_units': 7.273146238960692

!!python/unicode 'desc': !!python/unicode 'Residential Rent Hedonic'
