name: Residential Rent Hedonic

model_type: regression

fit_filters: null

predict_filters: null

model_expression: np.log1p(rent) ~ np.log1p(unit_sqft) + sum_residential_units + ave_unit_sqft
    + ave_lot_sqft + jobs

ytransform: np.exp

coefficients:
    Intercept: 2.1776372795070618
    ave_lot_sqft: 0.0053070252618946006
    ave_unit_sqft: -0.011882589349051596
    jobs: 0.014172463965846871
    np.log1p(unit_sqft): -0.19932107521431613
    sum_residential_units: 0.02414510318230409

fitted: true
