set_nan_price_to_zero: True

remove_invalid_building_ids: True

reconcile_residential_units_and_households: True

reconcile_non_residential_sqft_and_jobs: True

set_nan_price_to_zero: True

parcel_size_factor: 10.764

ave_sqft_per_unit_clip:
  lower: 800
  upper: 2500

enable_supply_correction:
  price_col: "residential_price"
  submarket_col: "zone_id"
  kwargs:
    clip_change_low: .8
    clip_change_high: 1.2
    iterations: 3

table_reprocess:
  buildings:
    filter: "building_type_id >= 1 and building_type_id <= 14"
    fill_nas:
      building_type_id:
        how: "drop"
        type: "int"
      residential_units:
        how: "zero"
        type: "int"
      non_residential_sqft:
        how: "zero"
        type: "int"
      year_built:
        how: "median"
        type: "int"
      building_type_id:
        how: "mode"
        type: "int"

rates:
  households_relocation: .05
  jobs_relocation: .05
  simple_households_transition: .02
  simple_jobs_transition: .02

build_networks:
  name: osm_bayarea.h5
  max_distance: 1500

households_transition:
  add_columns:
    - income_quartile
  total_column: total_number_of_households

jobs_transition:
  add_columns:
    - empsix_id
  total_column: number_of_jobs

feasibility:
  parcel_filter: oldest_building > 1940 and oldest_building < 2000
  residential_to_yearly: True
  pass_through:
    - oldest_building
    - total_sqft
    - max_far
    - max_dua
    - land_cost
    - residential
    - min_max_fars
    - max_far_from_dua
    - max_height
    - max_far_from_heights
    - building_purchase_price
    - building_purchase_price_sqft

residential_developer:
  target_vacancy: .13
  min_unit_size: 1000
  bldg_sqft_per_job: 400

non_residential_developer:
  target_vacancy: .49
  bldg_sqft_per_job: 400

pusher:
  key: 7d78b1b3454b78aed26f
  secret: d87736e21dd7819926e6
  host: http://localhost:8765/
  region: bayarea