name: residential units query

sort: true

metric: Sale_price_flt.mean()

filter: null

limit: 6

chart_type: multibarchart

table: homesales

orderdesc: false

groupby: City

jointoparcels: false

desc: Mean Sale_price_flt by city
