name: !!python/unicode 'mean_sale_price_flt_city'

!!python/unicode 'sort': true

!!python/unicode 'yscale': !!python/unicode '1'

!!python/unicode 'metric': !!python/unicode 'Sale_price_flt.mean()'

!!python/unicode 'groupby': !!python/unicode 'City'

!!python/unicode 'filter': null

!!python/unicode 'showXAxis': false

!!python/unicode 'limit': !!python/unicode '50'

!!python/unicode 'xAxisRotateLabels': !!python/unicode '90'

!!python/unicode 'charttype': !!python/unicode 'multibarchart'

!!python/unicode 'table': !!python/unicode 'homesales'

!!python/unicode 'orderdesc': true

!!python/unicode 'jointoparcels': false

!!python/unicode 'desc': !!python/unicode 'Mean Sale_price_flt by city'
