name: mean_sale_price_flt_city

sort: true

metric: Sale_price_flt.mean()

filter: null

limit: 6

chart_type: multibarchart

table: homesales

orderdesc: true

groupby: City

jointoparcels: false

desc: Mean Sale_price_flt by city
