name: mean_sale_price_flt_city

charttype: multibarchart

desc: Mean Sale_price_flt by city

table: homesales

filter: ''

groupby: city

metric: sale_price_flt.mean()

sort: true

orderdesc: false

limit: 50

showXAxis: false

xAxisRotateLabels: 90
