name: mean_sale_price_flt_zone

charttype: multibarchart

desc: Mean Sale_price_flt by zone

table: homesales

filter: sale_price_flt < inf

groupby: zone_id

metric: sale_price_flt.mean()

sort: true

orderdesc: true

limit: 0

showXAxis: false

xAxisRotateLabels: 0
